name: watch_next
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_dotenv: ^5.1.0
  flutter_typeahead: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  logger: ^1.4.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_shared: any
  path_provider: ^2.1.3
  isar_flutter_libs: ^4.0.0-dev.3
  mockito: ^5.4.4
  retry: ^3.1.2
  intl: ^0.19.0
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
 

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/

